server:
  port: 8081
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/seven_sso?stringtype=unspecified
      username: postgres
      password: postgres
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: ssoHikariCP
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
se:
  sso:
    cache:
      bean-name: redis
    redis:
      address: localhost:6379
      database: 1
    endpoint: http://127.0.0.1:8080
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 60000
